"""add iimage to package

Revision ID: 2bca0e2a369f
Revises: 62c4542e2e90
Create Date: 2026-04-17 14:39:27.444343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bca0e2a369f'
down_revision: Union[str, None] = '62c4542e2e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'image')
    # ### end Alembic commands ###
