"""add storage to claims

Revision ID: 370a67ed98df
Revises: 46f2cda565f2
Create Date: 2026-06-18 13:50:46.860901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370a67ed98df'
down_revision: Union[str, None] = '46f2cda565f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_of_incidents',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_storages',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('storage_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ),
    sa.PrimaryKeyConstraint('claim_id', 'storage_id')
    )
    op.add_column('claims', sa.Column('type_of_incident_id', sa.UUID(), nullable=True))
    op.add_column('claims', sa.Column('location_of_incidence', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'claims', 'type_of_incidents', ['type_of_incident_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'location_of_incidence')
    op.drop_column('claims', 'type_of_incident_id')
    op.drop_table('claim_storages')
    op.drop_table('type_of_incidents')
    # ### end Alembic commands ###
