"""add transport type to package

Revision ID: 62c4542e2e90
Revises: 6b36c1a2d65d
Create Date: 2026-04-17 13:22:57.889876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c4542e2e90'
down_revision: Union[str, None] = '6b36c1a2d65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('transport_type_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'packages', 'transport_types', ['transport_type_id'], ['id'])
    op.add_column('subscriptions', sa.Column('travel_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'travel_date')
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.drop_column('packages', 'transport_type_id')
    # ### end Alembic commands ###
