"""add literals

Revision ID: 6b36c1a2d65d
Revises: fcab882cf299
Create Date: 2026-04-15 16:03:38.041362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b36c1a2d65d'
down_revision: Union[str, None] = 'fcab882cf299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_types',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('subscriptions', sa.Column(
        'beneficiary_name', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column(
        'transport_type_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'transport_types', [
                          'transport_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'transport_type_id')
    op.drop_column('subscriptions', 'beneficiary_name')
    op.drop_table('transport_types')
    # ### end Alembic commands ###
