"""add more data to packages

Revision ID: e864a5406f1c
Revises: a44c5805326b
Create Date: 2026-03-02 07:38:37.890493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e864a5406f1c'
down_revision: Union[str, None] = 'a44c5805326b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('location_from', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('location_to', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'data')
    op.drop_column('subscriptions', 'location_to')
    op.drop_column('subscriptions', 'location_from')
    # ### end Alembic commands ###
