"""add is_testing_user

Revision ID: fcab882cf299
Revises: e864a5406f1c
Create Date: 2026-03-03 12:48:27.751273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcab882cf299'
down_revision: Union[str, None] = 'e864a5406f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_testing_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_testing_user')
    # ### end Alembic commands ###
